version: 1.0.{build}
skip_tags: true
skip_commits:
  message: /^chore(release)/
branches:
  only:
  - master
  - /preview\/*/ 
  - /release\/*/
image: 
- Visual Studio 2022
environment:
  GH_TOKEN: 
    secure: /o9VAhx5ewGmdLR9qcgFJMzBaCuzOmGlsXAHu7khUJLdQzsv4gJzLUfYDghcRPHd
  donetsdk: 9.0.100
init:
  - cmd: git config --global core.autocrlf true
install:
  - ps: Install-Product node 20 x64
  - ps: .\dotnet-install.ps1 -Version 8.0.403
  - ps: dotnet tool install --global GitVersion.Tool
  - ps: dotnet gitversion /l console /output buildserver
  - ps: .\dotnet-install.ps1 -Version $env:donetsdk
  - ps: ./appveyorinit.ps1
build_script:
  - ps: ./build.ps1
artifacts:
  - path: artifacts/**/*.nupkg
    name: nuget
deploy:
  - provider: NuGet
    api_key:
      secure: UCcGrUEujBVjkw4G9l6ebB4iWv8EBGNNP8FdzZQDT0GpGgCnaBRmmfdS+5ejk5EB
    on:
      branch: 
      - /preview\/*/
      - /release\/*/
      CI_WINDOWS: true
  - provider: GitHub
    auth_token: $(GH_TOKEN)
    draft: true
    prerelease: true
    release: $(Version)
    artifact: /.*\.nupkg/
    on:
      branch: 
      - /preview\/*/
      CI_WINDOWS: true
  - provider: GitHub
    auth_token: $(GH_TOKEN)
    draft: true
    release: $(Version)
    artifact: /.*\.nupkg/
    on:
      branch: 
      - /release\/*/
      CI_WINDOWS: true
for:
-
  branches:
    only:
      - /release\/*/
  on_success:
      - cmd: semantic-release -b %APPVEYOR_REPO_BRANCH%
